# Combining the Datasets

Combining both the Red & White Wine Datasets, as well as putting each value into their designated columns versus its original state.

In [5]:
# Importing the necessary applications:
from google.colab import files
uploaded = files.upload()
import pandas as pd
# Reading the datasets:
red = pd.read_csv("winequality-red.csv", sep = ";")
white = pd.read_csv("winequality-white.csv", sep = ";")

Saving winequality-red.csv to winequality-red (2).csv
Saving winequality-white.csv to winequality-white (2).csv

In [6]:
# Adding the wine type columns:
red["wine_type"] = "red"
white["wine_type"] = "white"

In [7]:
# Combining & cleaning the datasets with their columns for further accuracy.
wine_df = pd.concat([red, white], ignore_index = True)
wine_df.columns = wine_df.columns.str.strip().str.replace(" ", "_")

In [8]:
# Reviewing new combined dataset:
print("Shape:", wine_df.shape)
print(wine_df.head())

Shape: (6497, 13)
   fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076
1            7.8              0.88         0.00             2.6      0.098
2            7.8              0.76         0.04             2.3      0.092
3           11.2              0.28         0.56             1.9      0.075
4            7.4              0.70         0.00             1.9      0.076

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56
1                 25.0                  67.0   0.9968  3.20       0.68
2                 15.0                  54.0   0.9970  3.26       0.65
3                 17.0                  60.0   0.9980  3.16       0.58
4                 11.0                  34.0   0.9978  3.51       0.56

   alcohol  quality wine_type
0      9.4        5       red
1      9.8        5       red
2      9.8        5       red
3      9.8        6       red
4      9.4        5       red

In [9]:
# Saving the dataset & downloading it for further wrangling:
wine_df.to_csv("combined_wine_quality.csv")
files.download("combined_wine_quality.csv")
print("Dataset has been combined & downloaded successfully!")

Dataset has been combined & downloaded successfully!

# Cleaning the New Combined Dataset

Removing missing values as well as duplicates in order to prevent any unknown values from manipulating the data for later analyzation from the Data Scientist & Visualizer.

In [10]:
# Removing duplicates and showing values before and after as a way to check for any remaining:
print("Duplicates Before:", wine_df.duplicated().sum())
wine_df = wine_df.drop_duplicates()
print("Duplicates After:", wine_df.duplicated().sum())

Duplicates Before: 1177
Duplicates After: 0

In [12]:
# Although the duplicates have already likely taken care of the missing values, taking further measures to ensure there are no errors:
print("\nMissing Values Before:\n", wine_df.isnull().sum())
wine_df = wine_df.dropna()
print("\nMissing Values After:\n", wine_df.isnull().sum())

Missing Values Before:
 fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
wine_type               0
dtype: int64

Missing Values After:
 fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
wine_type               0
dtype: int64

In [14]:
# Additionally fixing the data types for the values designated categories:
wine_df["wine_type"] = wine_df["wine_type"].astype("category")

# Transforming the Wine Quality Dataset
Encoding categorical variables, scaling, and feature engineering the dataset in order to have a more effective and clearer visual for more efficient results.

In [15]:
# Encoding the categorical variables through binary means: red is 0, white is 1.
wine_df["wine_type_encoded"] = wine_df["wine_type"].map({"red": 0, "white": 1})

In [16]:
# Scaling the dataset to ensure future spitting, training, and testing of the data flows smoothly:
import numpy as np
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numeric_cols = wine_df.select_dtypes(include = np.number).columns
wine_df[numeric_cols] = scaler.fit_transform(wine_df[numeric_cols])

In [18]:
# Adding a feature engineering attribution for simpler analyzation of alcohol levels:
wine_df["alcohol+level"] = pd.cut(wine_df["alcohol"], bins = 3, labels = ["low", "medium", "high"])
wine_df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,wine_type,wine_type_encoded,alcohol+level
0,0.140064,2.115349,-2.164515,-0.699699,0.523880,-1.069272,-1.411143,1.100996,1.779304,0.177941,-0.969152,-0.904497,red,0,low
1,0.443199,3.185297,-2.164515,-0.544135,1.120736,-0.282905,-0.829839,0.763753,-0.153797,0.979389,-0.631833,-0.904497,red,0,low
2,0.443199,2.471998,-1.892672,-0.610806,0.957957,-0.844596,-1.058837,0.831202,0.220351,0.779027,-0.631833,-0.904497,red,0,low
3,3.019841,-0.381197,1.641293,-0.699699,0.496751,-0.732258,-0.953146,1.168444,-0.403229,0.311515,-0.631833,0.232268,red,0,low
5,0.140064,1.877583,-2.164515,-0.721923,0.496751,-0.956934,-1.305451,1.100996,1.779304,0.177941,-0.969152,-0.904497,red,0,low

# Assessing & Finalizing the Cleaned Dataset
Importing summary statistics, value counts, and checking the final shape to ensure there are no further errors and/or miscalculations.

In [20]:
# Importing Summary Statistics:
wine_df.describe()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
count,5.320000e+03,5.320000e+03,5.320000e+03,5320.000000,5.320000e+03,5.320000e+03,5.320000e+03,5.320000e+03,5.320000e+03,5.320000e+03,5.320000e+03,5.320000e+03
mean,3.205456e-16,-6.410912e-17,2.671213e-17,0.000000,1.282182e-16,2.136971e-17,-8.547883e-17,1.857027e-14,6.197215e-16,-2.136971e-17,6.624609e-16,3.419153e-16
std,1.000094e+00,1.000094e+00,1.000094e+00,1.000094,1.000094e+00,1.000094e+00,1.000094e+00,1.000094e+00,1.000094e+00,1.000094e+00,1.000094e+00,1.000094e+00
min,-2.588145e+00,-1.570028e+00,-2.164515e+00,-0.988604,-1.293816e+00,-1.630964e+00,-1.904371e+00,-2.504125e+00,-3.146985e+00,-2.092831e+00,-2.149768e+00,-3.178027e+00
25%,-6.177717e-01,-6.784048e-01,-5.334545e-01,-0.721923,-5.070517e-01,-7.884267e-01,-7.065318e-01,-7.875618e-01,-7.150198e-01,-6.902954e-01,-8.848223e-01,-9.044973e-01
50%,-1.630701e-01,-2.623138e-01,-5.772841e-02,-0.521912,-2.628836e-01,-1.143971e-01,3.331010e-02,3.868208e-02,-9.143899e-02,-1.559963e-01,-1.258547e-01,2.322676e-01
75%,3.674151e-01,3.915434e-01,5.539194e-01,0.544812,2.525824e-01,6.158017e-01,6.894794e-01,7.536359e-01,6.568580e-01,4.450903e-01,7.174425e-01,2.322676e-01
max,6.581671e+00,7.346207e+00,9.116989e+00,13.501067,1.503832e+01,1.454575e+01,5.740662e+00,1.498864e+01,4.897208e+00,9.795325e+00,3.668983e+00,3.642562e+00

In [21]:
# Importing Value Counts:
print("\nWine Type Distribution:\n", wine_df["wine_type"].value_counts())

Wine Type Distribution:
 wine_type
white    3961
red      1359
Name: count, dtype: int64

In [22]:
# Importing the finalized shape of the data:
print("\nFinal Shape:", wine_df.shape)
wine_df.head()

Final Shape: (5320, 15)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,wine_type,wine_type_encoded,alcohol+level
0,0.140064,2.115349,-2.164515,-0.699699,0.523880,-1.069272,-1.411143,1.100996,1.779304,0.177941,-0.969152,-0.904497,red,0,low
1,0.443199,3.185297,-2.164515,-0.544135,1.120736,-0.282905,-0.829839,0.763753,-0.153797,0.979389,-0.631833,-0.904497,red,0,low
2,0.443199,2.471998,-1.892672,-0.610806,0.957957,-0.844596,-1.058837,0.831202,0.220351,0.779027,-0.631833,-0.904497,red,0,low
3,3.019841,-0.381197,1.641293,-0.699699,0.496751,-0.732258,-0.953146,1.168444,-0.403229,0.311515,-0.631833,0.232268,red,0,low
5,0.140064,1.877583,-2.164515,-0.721923,0.496751,-0.956934,-1.305451,1.100996,1.779304,0.177941,-0.969152,-0.904497,red,0,low

In [23]:
# Saving & Downloading the Finalized Cleaned Dataset:
wine_df.to_csv("clean_wine_quality.csv", index = False)
files.download("clean_wine_quality.csv")

# Code Attribution:
Title: Project Two Data Wrangler Portion

Professor(s): Fadi Alsaleem & Catherine Williams

Date: 08 April 2026

Modified By: Faith Wade

Description: This program is used to combine, clean, transform, and assess multiple data sources in order to pass on a cleaned version to the data scientist and wrangler for further progression.
***
Title: Data Science Project Two

Professor(s): Fadi Alsaleem & Catherine Williams

Date: 08 April 2026

Modified By: Faith Wade

Description: This program was modified to take the wine quality datasets (red & white), and combine, clean, transform, and finally assess in order to pass on a cleaned version of the dataset to the data scientist (Silvia Rosario Betances) and data visualizer (Hana Sijad) for further progression.

Source(s):


https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

https://pandas.pydata.org/docs/user_guide/missing_data.html

https://scikit-learn.org/stable/modules/preprocessing.html

https://pandas.pydata.org/docs/user_guide/basics.html